name: Update flake inputs

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31

      - uses: DeterminateSystems/update-flake-lock@v28
        with:
          pr-title: "nix flake update"
          branch: automated/flake-update
