name: Update flake inputs

on:
  schedule:
    - cron: "0 0 * * 0" # Weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31

      - name: Update flake inputs
        run: nix flake update

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "nix flake update"
          title: "nix flake update"
          body: Automated flake input updates.
          branch: automated/flake-update
          delete-branch: true
